---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myspeed
  namespace: argocd
spec:
  destination:
    namespace: myspeed
    server: https://kubernetes.default.svc
  project: myspeed
  source:
    path: apps/myspeed
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.hostUsers'