---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
spec:
  destination:
    namespace: calibre
    server: https://kubernetes.default.svc
  project: calibre
  source:
    path: apps/calibre/application/apps
    repoURL: https://github.com/Franjly/argocd-homelab-pi-k3s.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true