---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: trivy-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: trivy-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Franjly/homelab-pi-k3s.git
  - https://github.com/Franjly/argocd-homelab-pi-k3s.git