---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  destination:
    namespace: tigera-operator
    server: https://kubernetes.default.svc
  project: calico
  source:
    path: system/calico
    plugin:
      name: kustomized-helm-v1.0
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: feature/upgrade-apps
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true