---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  destination:
    namespace: authelia
    server: https://kubernetes.default.svc
  project: authelia
  source:
    path: platform/authelia
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true