---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
spec:
  destination:
    namespace: pi-hole
    server: https://kubernetes.default.svc
  project: pi-hole
  source:
    path: apps/pi-hole
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true