---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  project: monitoring-system
  source:
    path: system/monitoring-system/kube-prometheus-stack
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: feature/upgrade-apps
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: '*'
      jqPathExpressions:
        - '.webhooks[]?.failurePolicy'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
