---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  project: monitoring-system
  source:
    path: system/monitoring-system/uptime-kuma
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true