---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: calico-metrics
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: calico-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Franjly/homelab-pi-k3s.git