---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-info
  namespace: argocd
spec:
  destination:
    namespace: pod-info
    server: https://kubernetes.default.svc
  project: pod-info
  source:
    path: apps/pod-info
    plugin:
      name: vault-kustomized
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true