---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-system
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: kyverno
  source:
    path: system/kyverno/application/apps
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/argocd-homelab-pi-k3s.git
    targetRevision: feature/upgrade-apps-2024
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true