---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-system
  namespace: argocd
spec:
  destination:
    namespace: trivy-system
    server: https://kubernetes.default.svc
  project: trivy-system
  source:
    path: platform/trivy-system/application/apps
    repoURL: https://github.com/Franjly/argocd-homelab-pi-k3s.git
    targetRevision: feature/upgrade-apps-2024
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true